'use client';

import { FormEvent, useEffect, useMemo, useState } from 'react';
import { PageHeader, StatusBadge } from './ui';

type Kind='categories'|'collections';
type Resource={id:string;name:string;slug:string;description:string;status:string;product_count:number;seo_title?:string|null;seo_description?:string|null;parent_id?:string|null;merchandising_mode?:string;collection_type?:string;rules?:Rule[];product_ids?:string[]};
type Rule={field:'margin_percent'|'category'|'stock'|'featured'|'supplier';operator:'eq'|'gt'|'gte'|'lt'|'lte';value:string|number|boolean};
type Product={id:string;title:string;status:string};
const empty={name:'',slug:'',description:'',seo_title:'',seo_description:'',parent_id:'',status:'draft',merchandising_mode:'manual',collection_type:'manual',rules:[] as Rule[],product_ids:[] as string[]};

export default function CommerceResourceManager({kind}:{kind:Kind}){
  const [items,setItems]=useState<Resource[]>([]);const [products,setProducts]=useState<Product[]>([]);const [form,setForm]=useState({...empty});const [editing,setEditing]=useState<string|null>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('');const [productSearch,setProductSearch]=useState('');
  const isCategory=kind==='categories';
  async function load(){setLoading(true);const response=await fetch(`/api/admin/${kind}`);const payload=await response.json();if(payload.success)setItems(payload.data||[]);setLoading(false);}
  useEffect(()=>{load();if(!isCategory)fetch('/api/products?status=all&limit=200').then(r=>r.json()).then(p=>setProducts(p.data?.items||[])).catch(()=>undefined);},[kind]);
  const visibleProducts=useMemo(()=>products.filter(product=>product.title.toLowerCase().includes(productSearch.toLowerCase())).slice(0,30),[products,productSearch]);
  function setName(name:string){setForm(value=>({...value,name,slug:editing?value.slug:slugify(name)}));}
  function edit(item:Resource){setEditing(item.id);setForm({name:item.name,slug:item.slug,description:item.description||'',seo_title:item.seo_title||'',seo_description:item.seo_description||'',parent_id:item.parent_id||'',status:item.status,merchandising_mode:item.merchandising_mode||'manual',collection_type:item.collection_type||'manual',rules:item.rules||[],product_ids:item.product_ids||[]});setError('');window.scrollTo({top:0,behavior:'smooth'});}
  function reset(){setEditing(null);setForm({...empty});setError('');}
  async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');const response=await fetch(`/api/admin/${kind}`,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,id:editing||undefined,sort_order:editing?items.findIndex(item=>item.id===editing):items.length})});const payload=await response.json();setSaving(false);if(!response.ok){setError(payload.error||'No se pudo guardar');return;}reset();load();}
  async function remove(item:Resource){if(!window.confirm(`¿Eliminar “${item.name}”?`))return;await fetch(`/api/admin/${kind}?id=${item.id}`,{method:'DELETE'});if(editing===item.id)reset();load();}
  function toggleProduct(id:string){setForm(value=>({...value,product_ids:value.product_ids.includes(id)?value.product_ids.filter(current=>current!==id):[...value.product_ids,id]}));}
  function setRule(part:Partial<Rule>){setForm(value=>({...value,rules:[{field:'margin_percent',operator:'gt',value:40,...(value.rules[0]||{}),...part}]}));}
  const title=isCategory?'Categorías':'Colecciones';
  return <div className="admin-page admin-commerce-page"><PageHeader eyebrow="Contenido" title={title} description={isCategory?'Organiza el catálogo, SEO y orden de merchandising.':'Agrupa productos manualmente o mediante reglas automáticas.'}/>
    <div className="admin-commerce-layout"><form className="admin-panel admin-editor-card" onSubmit={submit}><header><h2>{editing?`Editar ${isCategory?'categoría':'colección'}`:`Nueva ${isCategory?'categoría':'colección'}`}</h2>{editing&&<button type="button" onClick={reset}>Cancelar</button>}</header>
      <label>Nombre<input value={form.name} onChange={event=>setName(event.target.value)} required minLength={2}/></label>
      <label>Slug<input value={form.slug} onChange={event=>setForm(value=>({...value,slug:event.target.value}))} required pattern="[a-z0-9]+(?:-[a-z0-9]+)*"/></label>
      <label>Descripción<textarea value={form.description} onChange={event=>setForm(value=>({...value,description:event.target.value}))} rows={3}/></label>
      {isCategory&&<><label>Categoría superior<select value={form.parent_id} onChange={event=>setForm(value=>({...value,parent_id:event.target.value}))}><option value="">Sin categoría superior</option>{items.filter(item=>item.id!==editing).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label>Título SEO<input value={form.seo_title} maxLength={70} onChange={event=>setForm(value=>({...value,seo_title:event.target.value}))} placeholder="Hasta 70 caracteres"/></label><label>Descripción SEO<textarea value={form.seo_description} maxLength={170} onChange={event=>setForm(value=>({...value,seo_description:event.target.value}))} rows={2}/></label></>}
      <div className="admin-form-grid"><label>Estado<select value={form.status} onChange={event=>setForm(value=>({...value,status:event.target.value}))}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="archived">Archivado</option></select></label>
      {isCategory?<label>Orden de productos<select value={form.merchandising_mode} onChange={event=>setForm(value=>({...value,merchandising_mode:event.target.value}))}><option value="manual">Manual</option><option value="newest">Más nuevos</option><option value="best_sellers">Más vendidos</option><option value="highest_margin">Mayor margen</option><option value="trending">Tendencia</option></select></label>:<label>Tipo<select value={form.collection_type} onChange={event=>setForm(value=>({...value,collection_type:event.target.value}))}><option value="manual">Manual</option><option value="automatic">Automática</option></select></label>}</div>
      {!isCategory&&form.collection_type==='automatic'&&<div className="admin-rule-builder"><strong>Regla automática</strong><div><select value={form.rules[0]?.field||'margin_percent'} onChange={e=>setRule({field:e.target.value as Rule['field']})}><option value="margin_percent">Margen</option><option value="category">Categoría</option><option value="stock">Stock</option><option value="featured">Destacado</option><option value="supplier">Proveedor</option></select><select value={form.rules[0]?.operator||'gt'} onChange={e=>setRule({operator:e.target.value as Rule['operator']})}><option value="eq">es igual a</option><option value="gt">mayor que</option><option value="gte">igual o mayor</option><option value="lt">menor que</option><option value="lte">igual o menor</option></select><input value={String(form.rules[0]?.value??40)} onChange={e=>setRule({value:Number.isNaN(Number(e.target.value))?e.target.value:Number(e.target.value)})}/></div></div>}
      {!isCategory&&form.collection_type==='manual'&&<div className="admin-product-picker"><strong>Productos ({form.product_ids.length})</strong><input placeholder="Buscar producto…" value={productSearch} onChange={e=>setProductSearch(e.target.value)}/><div>{visibleProducts.map(product=><label key={product.id}><input type="checkbox" checked={form.product_ids.includes(product.id)} onChange={()=>toggleProduct(product.id)}/><span>{product.title}</span></label>)}</div></div>}
      {error&&<p className="admin-form-error" role="alert">{error}</p>}<button className="admin-button is-accent" disabled={saving}>{saving?'Guardando…':editing?'Guardar cambios':'Crear'}</button>
    </form>
    <section className="admin-panel admin-resource-list"><header><h2>{title}</h2><span>{items.length} registros</span></header>{loading?<div className="admin-empty">Cargando…</div>:items.length===0?<div className="admin-empty">Aún no hay registros.</div>:items.map(item=><article key={item.id}><button className="admin-resource-main" onClick={()=>edit(item)}><span><strong>{item.name}</strong><small>/{item.slug} · {item.product_count||0} productos</small></span><StatusBadge value={item.status}/></button><button className="admin-resource-delete" onClick={()=>remove(item)} aria-label={`Eliminar ${item.name}`}>×</button></article>)}</section></div>
  </div>;
}
function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().trim().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,100);}
