'use client';

import { FormEvent, useEffect, useState } from 'react';
type Variant={id:string;title:string;sku?:string|null;price_usd?:number|null;price_cop?:number|null;stock:number;status:string};
type Media={usage_id:string;id:string;kind:'image'|'video'|'audio'|'document';url:string;title:string;role:string;metadata?:{provider?:string}};
const variantBlank={title:'',sku:'',price_usd:'',price_cop:'',stock:'0',status:'active'};
const mediaBlank={url:'',title:'',role:'video'};

export default function ProductCommercePanels({productId,isNew}:{productId:string;isNew:boolean}){const [variants,setVariants]=useState<Variant[]>([]);const [media,setMedia]=useState<Media[]>([]);const [variant,setVariant]=useState({...variantBlank});const [asset,setAsset]=useState({...mediaBlank});const [error,setError]=useState('');const [saving,setSaving]=useState(false);
async function load(){if(isNew)return;const [variantsResponse,mediaResponse]=await Promise.all([fetch(`/api/admin/products/${productId}/variants`),fetch(`/api/admin/products/${productId}/media`)]);const [variantsPayload,mediaPayload]=await Promise.all([variantsResponse.json(),mediaResponse.json()]);if(variantsPayload.success)setVariants(variantsPayload.data||[]);if(mediaPayload.success)setMedia(mediaPayload.data||[]);}useEffect(()=>{load();},[productId,isNew]);
async function addVariant(event:FormEvent){event.preventDefault();setSaving(true);setError('');const response=await fetch(`/api/admin/products/${productId}/variants`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...variant,price_usd:variant.price_usd?Number(variant.price_usd):null,price_cop:variant.price_cop?Number(variant.price_cop):null,stock:Number(variant.stock),option_values:{}})});const payload=await response.json();setSaving(false);if(!response.ok){setError(payload.error||'No se pudo crear la variante');return;}setVariant({...variantBlank});load();}
async function addMedia(event:FormEvent){event.preventDefault();setSaving(true);setError('');const response=await fetch(`/api/admin/products/${productId}/media`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(asset)});const payload=await response.json();setSaving(false);if(!response.ok){setError(payload.error||'No se pudo añadir el recurso');return;}setAsset({...mediaBlank});load();}
async function removeVariant(id:string){if(!window.confirm('¿Eliminar esta variante?'))return;await fetch(`/api/admin/products/${productId}/variants?variantId=${id}`,{method:'DELETE'});load();}
async function removeMedia(id:string){await fetch(`/api/admin/products/${productId}/media?usageId=${id}`,{method:'DELETE'});load();}
if(isNew)return <section className="admin-product-module"><header><div><h2>Variantes y multimedia</h2><p>Guarda el producto para habilitar estos módulos.</p></div></header></section>;
return <><section className="admin-product-module"><header><div><h2>Variantes</h2><p>Tallas, ediciones, formatos o presentaciones con SKU, precio y stock propios.</p></div><span>{variants.length}</span></header><form className="admin-inline-form admin-variant-form" onSubmit={addVariant}><input aria-label="Nombre de variante" placeholder="Ej. Tapa dura" value={variant.title} onChange={e=>setVariant(v=>({...v,title:e.target.value}))} required/><input aria-label="SKU" placeholder="SKU" value={variant.sku} onChange={e=>setVariant(v=>({...v,sku:e.target.value}))}/><input aria-label="Precio USD" type="number" step="0.01" min="0" placeholder="USD" value={variant.price_usd} onChange={e=>setVariant(v=>({...v,price_usd:e.target.value}))}/><input aria-label="Precio COP" type="number" min="0" placeholder="COP" value={variant.price_cop} onChange={e=>setVariant(v=>({...v,price_cop:e.target.value}))}/><input aria-label="Stock" type="number" min="-1" placeholder="Stock" value={variant.stock} onChange={e=>setVariant(v=>({...v,stock:e.target.value}))}/><button disabled={saving}>Añadir</button></form>{variants.length===0?<div className="admin-module-empty">Este producto no tiene variantes.</div>:<div className="admin-variant-list">{variants.map(item=><article key={item.id}><span><strong>{item.title}</strong><small>{item.sku||'Sin SKU'} · {item.stock===-1?'Ilimitado':`${item.stock} unidades`}</small></span><b>{item.price_cop?`$${Number(item.price_cop).toLocaleString('es-CO')}`:item.price_usd?`$${Number(item.price_usd).toFixed(2)} USD`:'Precio base'}</b><button onClick={()=>removeVariant(item.id)}>×</button></article>)}</div>}</section>
<section className="admin-product-module"><header><div><h2>Multimedia del producto</h2><p>YouTube, Vimeo, Spotify, SoundCloud o archivos HTML5 validados.</p></div><span>{media.length}</span></header><form className="admin-inline-form admin-media-inline" onSubmit={addMedia}><input type="url" aria-label="URL multimedia" placeholder="Pega una URL HTTPS…" value={asset.url} onChange={e=>setAsset(v=>({...v,url:e.target.value}))} required/><input aria-label="Título del recurso" placeholder="Título" value={asset.title} onChange={e=>setAsset(v=>({...v,title:e.target.value}))}/><select aria-label="Rol" value={asset.role} onChange={e=>setAsset(v=>({...v,role:e.target.value}))}><option value="video">Video</option><option value="audio">Audio</option><option value="embed">Embed</option><option value="gallery">Galería</option></select><button disabled={saving}>Añadir</button></form>{error&&<p className="admin-form-error">{error}</p>}{media.length===0?<div className="admin-module-empty">Añade una demostración, preview o contenido editorial.</div>:<div className="admin-product-media-list">{media.map(item=><article key={item.usage_id}><MediaPreview item={item}/><span><strong>{item.title||item.kind}</strong><small>{item.metadata?.provider||item.kind} · {item.role}</small></span><button onClick={()=>removeMedia(item.usage_id)}>×</button></article>)}</div>}</section></>;
}

function MediaPreview({item}:{item:Media}){const provider=item.metadata?.provider;if(provider&&provider!=='html5'&&provider!=='image')return <iframe src={item.url} title={item.title||'Recurso multimedia'} loading="lazy" allow="autoplay; encrypted-media; picture-in-picture"/>;if(item.kind==='video')return <video src={item.url} controls preload="metadata"/>;if(item.kind==='audio')return <audio src={item.url} controls preload="metadata"/>;if(item.kind==='image')return <img src={item.url} alt="" loading="lazy"/>;return <span className="admin-media-file">DOC</span>;}
