import { randomUUID } from 'node:crypto';
import { NextRequest, NextResponse } from 'next/server';
import { requireAdmin } from '@/lib/auth';
import { query } from '@/lib/db';
import { variantSchema } from '@/modules/catalog/schemas';

export async function GET(req:NextRequest,{params}:{params:{id:string}}){const auth=await requireAdmin(req);if(auth)return auth;const rows=await query(`SELECT * FROM product_variants WHERE product_id=$1 AND status<>'archived' ORDER BY sort_order,created_at`,[params.id]);return NextResponse.json({success:true,data:rows.rows});}
export async function POST(req:NextRequest,{params}:{params:{id:string}}){return save(req,params.id,false);}
export async function PUT(req:NextRequest,{params}:{params:{id:string}}){return save(req,params.id,true);}
async function save(req:NextRequest,productId:string,update:boolean){const auth=await requireAdmin(req);if(auth)return auth;const parsed=(update?variantSchema.required({id:true}):variantSchema).safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({success:false,error:parsed.error.issues[0]?.message||'Datos inválidos'},{status:400});const v=parsed.data;const id=v.id||randomUUID();const row=update?await query(`UPDATE product_variants SET title=$3,sku=$4,option_values=$5,price_usd=$6,price_cop=$7,stock=$8,status=$9,sort_order=$10,updated_at=NOW() WHERE id=$1 AND product_id=$2 RETURNING *`,[id,productId,v.title,v.sku||null,JSON.stringify(v.option_values),v.price_usd??null,v.price_cop??null,v.stock,v.status,v.sort_order]):await query(`INSERT INTO product_variants(id,product_id,title,sku,option_values,price_usd,price_cop,stock,status,sort_order) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10) RETURNING *`,[id,productId,v.title,v.sku||null,JSON.stringify(v.option_values),v.price_usd??null,v.price_cop??null,v.stock,v.status,v.sort_order]);return NextResponse.json({success:true,data:row.rows[0]},{status:update?200:201});}
export async function DELETE(req:NextRequest,{params}:{params:{id:string}}){const auth=await requireAdmin(req);if(auth)return auth;const variantId=new URL(req.url).searchParams.get('variantId');if(!variantId)return NextResponse.json({success:false,error:'ID requerido'},{status:400});await query(`UPDATE product_variants SET status='archived',updated_at=NOW() WHERE id=$1 AND product_id=$2`,[variantId,params.id]);return NextResponse.json({success:true});}
