'use client';

import { FormEvent, useEffect, useState } from 'react';
import { PageHeader, StatusBadge } from '@/components/admin/ui';

type Section={id:string;page_key:string;section_type:string;name:string;status:string;position:number;config:Record<string,unknown>;scheduled_at?:string|null;expires_at?:string|null};
const TYPES=[['hero','Hero'],['featured_products','Productos destacados'],['product_carousel','Carrusel de productos'],['categories','Categorías'],['image_grid','Grid de imágenes'],['video','Video'],['audio','Audio'],['testimonials','Testimonios'],['faq','FAQ'],['newsletter','Newsletter'],['banner','Banner'],['text','Texto'],['promo','Promoción'],['brands','Marcas'],['reviews','Reseñas']];
const blank={page_key:'homepage',section_type:'hero',name:'',status:'draft',position:0,config:{heading:'',text:'',media_url:'',cta_label:'',cta_url:''},scheduled_at:'',expires_at:''};

export default function SectionsPage(){const [items,setItems]=useState<Section[]>([]);const [form,setForm]=useState({...blank});const [editing,setEditing]=useState<string|null>(null);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
async function load(){const response=await fetch(`/api/admin/sections?page=${form.page_key}`);const payload=await response.json();if(payload.success)setItems(payload.data||[]);}useEffect(()=>{load();},[form.page_key]);
function reset(){setEditing(null);setForm(value=>({...blank,page_key:value.page_key,position:items.length}));setError('');}
function edit(item:Section){setEditing(item.id);setForm({page_key:item.page_key,section_type:item.section_type,name:item.name,status:item.status,position:item.position,config:{...blank.config,...item.config},scheduled_at:toLocal(item.scheduled_at),expires_at:toLocal(item.expires_at)});window.scrollTo({top:0,behavior:'smooth'});}
async function save(event:FormEvent){event.preventDefault();setSaving(true);setError('');const payload={...form,id:editing||undefined,position:editing?form.position:items.length,scheduled_at:form.scheduled_at?new Date(form.scheduled_at).toISOString():null,expires_at:form.expires_at?new Date(form.expires_at).toISOString():null};const response=await fetch('/api/admin/sections',{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json();setSaving(false);if(!response.ok){setError(data.error||'No se pudo guardar');return;}reset();load();}
async function update(item:Section,patch:Partial<Section>){await fetch('/api/admin/sections',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...item,...patch,scheduled_at:item.scheduled_at||null,expires_at:item.expires_at||null})});}
async function move(index:number,direction:-1|1){const target=index+direction;if(target<0||target>=items.length)return;const a=items[index],b=items[target];await Promise.all([update(a,{position:b.position}),update(b,{position:a.position})]);load();}
async function duplicate(item:Section){await fetch('/api/admin/sections',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...item,id:undefined,name:`${item.name} copia`,status:'draft',position:items.length,scheduled_at:null,expires_at:null})});load();}
async function remove(item:Section){if(!window.confirm(`¿Eliminar “${item.name}”?`))return;await fetch(`/api/admin/sections?id=${item.id}`,{method:'DELETE'});load();}
function setConfig(key:string,value:string){setForm(current=>({...current,config:{...current.config,[key]:value}}));}
return <div className="admin-page admin-commerce-page"><PageHeader eyebrow="Storefront Builder" title="Secciones" description="Construye el homepage con bloques ordenables, multimedia y programación."/>
<div className="admin-commerce-layout"><form className="admin-panel admin-editor-card" onSubmit={save}><header><h2>{editing?'Editar sección':'Añadir sección'}</h2>{editing&&<button type="button" onClick={reset}>Cancelar</button>}</header><div className="admin-form-grid"><label>Página<select value={form.page_key} onChange={e=>setForm(v=>({...v,page_key:e.target.value}))}><option value="homepage">Homepage</option><option value="catalog">Catálogo</option></select></label><label>Tipo<select value={form.section_type} onChange={e=>setForm(v=>({...v,section_type:e.target.value}))}>{TYPES.map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div><label>Nombre interno<input value={form.name} onChange={e=>setForm(v=>({...v,name:e.target.value}))} required/></label><label>Heading<input value={String(form.config.heading||'')} onChange={e=>setConfig('heading',e.target.value)}/></label><label>Texto<textarea value={String(form.config.text||'')} onChange={e=>setConfig('text',e.target.value)} rows={3}/></label><label>Media URL<input type="url" value={String(form.config.media_url||'')} onChange={e=>setConfig('media_url',e.target.value)} placeholder="https://…"/></label><div className="admin-form-grid"><label>CTA<input value={String(form.config.cta_label||'')} onChange={e=>setConfig('cta_label',e.target.value)}/></label><label>URL del CTA<input value={String(form.config.cta_url||'')} onChange={e=>setConfig('cta_url',e.target.value)}/></label></div><div className="admin-form-grid"><label>Estado<select value={form.status} onChange={e=>setForm(v=>({...v,status:e.target.value}))}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="hidden">Oculto</option></select></label><label>Publicar desde<input type="datetime-local" value={form.scheduled_at} onChange={e=>setForm(v=>({...v,scheduled_at:e.target.value}))}/></label></div><label>Ocultar después<input type="datetime-local" value={form.expires_at} onChange={e=>setForm(v=>({...v,expires_at:e.target.value}))}/></label>{error&&<p className="admin-form-error">{error}</p>}<button className="admin-button is-accent" disabled={saving}>{saving?'Guardando…':editing?'Guardar cambios':'Añadir sección'}</button></form>
<section className="admin-panel admin-sections-list"><header><h2>Orden en {form.page_key==='homepage'?'Homepage':'Catálogo'}</h2><span>{items.length} bloques</span></header>{items.length===0?<div className="admin-empty">Añade la primera sección.</div>:items.map((item,index)=><article key={item.id}><div className="admin-section-order"><button onClick={()=>move(index,-1)} disabled={index===0} aria-label="Subir">↑</button><button onClick={()=>move(index,1)} disabled={index===items.length-1} aria-label="Bajar">↓</button></div><button className="admin-resource-main" onClick={()=>edit(item)}><span><strong>{item.name}</strong><small>{TYPES.find(type=>type[0]===item.section_type)?.[1]||item.section_type} · posición {index+1}</small></span><StatusBadge value={item.status}/></button><div className="admin-section-actions"><button onClick={()=>update(item,{status:item.status==='hidden'?'draft':'hidden'}).then(load)}>{item.status==='hidden'?'Mostrar':'Ocultar'}</button><button onClick={()=>duplicate(item)}>Duplicar</button><button onClick={()=>remove(item)}>Eliminar</button></div></article>)}</section></div></div>;
}
function toLocal(value?:string|null){if(!value)return '';const date=new Date(value);const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60000).toISOString().slice(0,16);}
