import { randomUUID } from 'node:crypto';
import { NextRequest, NextResponse } from 'next/server';
import { requireAdmin } from '@/lib/auth';
import { query, withTransaction } from '@/lib/db';
import { classifyMediaUrl, productMediaSchema } from '@/modules/media/embed';

export async function GET(req:NextRequest,{params}:{params:{id:string}}){const auth=await requireAdmin(req);if(auth)return auth;const rows=await query(`SELECT mu.id AS usage_id,mu.role,mu.sort_order,ma.id,ma.kind,ma.url,ma.title,ma.alt_text,ma.metadata FROM media_usages mu JOIN media_assets ma ON ma.id=mu.asset_id WHERE mu.entity_type='product' AND mu.entity_id=$1 ORDER BY mu.sort_order,mu.created_at`,[params.id]);return NextResponse.json({success:true,data:rows.rows});}
export async function POST(req:NextRequest,{params}:{params:{id:string}}){const auth=await requireAdmin(req);if(auth)return auth;const parsed=productMediaSchema.safeParse(await req.json().catch(()=>null));if(!parsed.success)return NextResponse.json({success:false,error:parsed.error.issues[0]?.message||'Datos inválidos'},{status:400});try{const v=parsed.data;const result=await withTransaction(async client=>{const product=await client.query('SELECT id FROM products WHERE id=$1',[params.id]);if(!product.rows[0])throw new Error('Producto no encontrado');let assetId=v.asset_id;if(!assetId&&v.url){const classified=classifyMediaUrl(v.url);assetId=randomUUID();const asset=await client.query(`INSERT INTO media_assets(id,kind,url,title,alt_text,storage_provider,source,metadata) VALUES($1,$2,$3,$4,$5,'external','product',$6) ON CONFLICT(url) DO UPDATE SET updated_at=NOW() RETURNING id`,[assetId,v.kind||classified.kind,classified.safeUrl,v.title,v.alt_text,JSON.stringify({provider:classified.provider,original_url:v.url})]);assetId=asset.rows[0].id;}const usage=await client.query(`INSERT INTO media_usages(id,asset_id,entity_type,entity_id,role,sort_order) VALUES($1,$2,'product',$3,$4,(SELECT COUNT(*) FROM media_usages WHERE entity_type='product' AND entity_id=$3)) ON CONFLICT(asset_id,entity_type,entity_id,role) DO UPDATE SET sort_order=media_usages.sort_order RETURNING *`,[randomUUID(),assetId,params.id,v.role]);return usage.rows[0];});return NextResponse.json({success:true,data:result},{status:201});}catch(error){return NextResponse.json({success:false,error:error instanceof Error?error.message:'No se pudo añadir el recurso'},{status:400});}}
export async function DELETE(req:NextRequest,{params}:{params:{id:string}}){const auth=await requireAdmin(req);if(auth)return auth;const usageId=new URL(req.url).searchParams.get('usageId');if(!usageId)return NextResponse.json({success:false,error:'ID requerido'},{status:400});await query(`DELETE FROM media_usages WHERE id=$1 AND entity_type='product' AND entity_id=$2`,[usageId,params.id]);return NextResponse.json({success:true});}
