'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { MetricCard, PageHeader, PanelHeader, StatusBadge } from '@/components/admin/ui';
type Connection={provider:string;display_name:string;configured:boolean;status:string;mode:string;last_error?:string|null};
type Transaction={id:string;order_id?:string|null;order_number?:string|null;provider:string;external_id:string;status:string;amount_minor:number;currency:string;payment_method?:string|null;occurred_at:string};
type Data={range_days:number;summary:{approved_count:number;pending_count:number;failed_count:number};volumes:{currency:string;gross_minor:number;fees_minor:number}[];connections:Connection[];transactions:Transaction[];refunds:unknown[];webhooks:{total:number;failed:number;last_event?:string|null}};

export default function PaymentsPage(){const [data,setData]=useState<Data|null>(null);const [days,setDays]=useState(30);useEffect(()=>{fetch(`/api/admin/payments?days=${days}`).then(r=>r.json()).then(payload=>{if(payload.success)setData(payload.data);}).catch(()=>undefined);},[days]);const volume=data?.volumes.map(item=>formatMinor(item.gross_minor,item.currency)).join(' · ')||'$0';
return <div className="admin-page"><PageHeader eyebrow="Commerce" title="Payments Hub" description="Pasarelas, transacciones, reembolsos y salud de webhooks en un solo lugar."><select className="admin-range-select" value={days} onChange={e=>setDays(Number(e.target.value))}><option value="7">7 días</option><option value="30">30 días</option><option value="90">90 días</option><option value="365">1 año</option></select></PageHeader>
<section className="admin-metrics"><MetricCard label="Volumen aprobado" value={volume} detail={`Últimos ${days} días`} tone={(data?.summary.approved_count||0)>0?'good':'neutral'}/><MetricCard label="Pagos aprobados" value={String(data?.summary.approved_count||0)} detail="Transacciones confirmadas" tone="good"/><MetricCard label="Pendientes" value={String(data?.summary.pending_count||0)} detail="Esperan confirmación" tone={(data?.summary.pending_count||0)>0?'warning':'good'}/><MetricCard label="Requieren revisión" value={String(data?.summary.failed_count||0)} detail={`${data?.webhooks.failed||0} webhooks fallidos`} tone={(data?.summary.failed_count||0)>0?'critical':'good'}/></section>
<section className="admin-panel admin-gateways"><PanelHeader title="Pasarelas" detail="Las credenciales permanecen en variables seguras del servidor" href="/admin/configuracion" action="Configuración"/><div>{data?.connections.map(connection=><article key={connection.provider}><span className={`admin-gateway-logo is-${connection.provider}`}>{connection.display_name.slice(0,2).toUpperCase()}</span><span><strong>{connection.display_name}</strong><small>{connection.configured?`${connection.mode==='sandbox'?'Sandbox':'Producción'} · credenciales detectadas`:'No conectada'}</small></span><StatusBadge value={connection.status}/></article>)||<div className="admin-empty">Cargando pasarelas…</div>}</div></section>
<section className="admin-panel"><PanelHeader title="Transacciones" detail="Registro normalizado de todos los proveedores"/>{!data?<div className="admin-empty">Cargando transacciones…</div>:data.transactions.length===0?<div className="admin-empty">Aún no hay transacciones registradas.</div>:<div className="admin-table-wrap"><table className="admin-data-table"><thead><tr><th>Transacción</th><th>Pedido</th><th>Proveedor</th><th>Estado</th><th>Fecha</th><th>Monto</th></tr></thead><tbody>{data.transactions.map(transaction=><tr key={transaction.id}><td><strong>{transaction.external_id}</strong><small>{transaction.payment_method||'Método no informado'}</small></td><td>{transaction.order_id?<Link href={`/admin/pedidos/${transaction.order_id}`}>#{transaction.order_number||transaction.order_id.slice(0,8)}</Link>:'Sin pedido'}</td><td>{transaction.provider}</td><td><StatusBadge value={transaction.status}/></td><td>{new Date(transaction.occurred_at).toLocaleDateString('es-CO')}</td><td><strong>{formatMinor(transaction.amount_minor,transaction.currency)}</strong></td></tr>)}</tbody></table></div>}</section>
<section className="admin-payment-foot"><div className="admin-panel"><PanelHeader title="Reembolsos" detail="Historial consolidado"/><div className="admin-empty">{data?.refunds.length?`${data.refunds.length} reembolsos registrados`:'No hay reembolsos registrados.'}</div></div><div className="admin-panel"><PanelHeader title="Webhooks" detail="Últimos eventos recibidos"/><div className="admin-webhook-health"><strong>{data?.webhooks.total||0}</strong><span>eventos · {data?.webhooks.failed||0} fallidos</span><i className={(data?.webhooks.failed||0)>0?'is-warning':'is-good'}/></div></div></section></div>;
}
function formatMinor(value:number,currency:string){const amount=currency==='COP'?Number(value):Number(value)/100;return new Intl.NumberFormat('es-CO',{style:'currency',currency,maximumFractionDigits:currency==='COP'?0:2}).format(amount);}
